# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

FROM rust:slim-bookworm AS builder

RUN mkdir /opentalk-roomserver
WORKDIR /opentalk-roomserver

ADD . /opentalk-roomserver

RUN apt-get update && apt-get full-upgrade -y && \
    apt-get install --no-install-recommends -y ca-certificates pkg-config libssl-dev curl

RUN cargo build --release --locked

FROM ubuntu:noble

RUN apt-get update && apt-get full-upgrade -y && \
    apt-get install --no-install-recommends -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ENV USERID=1000
ENV GROUPID=1000

RUN mkdir /opentalk-roomserver
WORKDIR /opentalk-roomserver

COPY --from=builder /opentalk-roomserver/target/release/opentalk-roomserver .
COPY --from=builder /opentalk-roomserver/example/roomserver.toml roomserver.toml

USER $USERID:$GROUPID

EXPOSE 11333
ENTRYPOINT [ "./opentalk-roomserver" ]
