// SPDX-License-Identifier: EUPL-1.2
// SPDX-FileCopyrightText: OpenTalk Team <mail@opentalk.eu>

use opentalk_types_api_v1::users::PublicUserProfile;
use opentalk_types_common::{users::DisplayName, utils::ExampleData};
use serde::{Deserialize, Serialize};

/// Client context required for a signaling connection
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "utoipa", derive(utoipa::ToSchema), schema(example = json!(ClientParameters::example_data())))]
pub struct ClientParameters {
    /// Identifier to maintain participant state across reconnections, is generated by the client
    pub device_secret: String,

    /// Information about a registered user
    #[serde(flatten)]
    pub kind: ClientKind,

    /// The role that the client assumes in the meeting.
    pub role: Role,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "utoipa", derive(utoipa::ToSchema))]
#[serde(rename_all = "snake_case", tag = "kind")]
pub enum ClientKind {
    /// A registered user
    Registered { profile: PublicUserProfile },

    /// A guest participant
    Guest { display_name: DisplayName },
}

impl ExampleData for ClientParameters {
    fn example_data() -> Self {
        Self {
            device_secret: "string".into(),
            kind: ClientKind::Registered {
                profile: PublicUserProfile::example_data(),
            },
            role: Role::Moderator,
        }
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "utoipa", derive(utoipa::ToSchema))]
#[serde(rename_all = "snake_case")]
pub enum Role {
    User,
    Moderator,
}

#[cfg(test)]
mod tests {
    use opentalk_types_api_v1::users::PublicUserProfile;
    use opentalk_types_common::{users::DisplayName, utils::ExampleData};
    use serde_json::json;

    use super::ClientKind;
    use crate::client_parameters::{ClientParameters, Role};

    #[test]
    fn guest() {
        let value = serde_json::to_value(ClientParameters {
            device_secret: "1234".into(),
            kind: ClientKind::Guest {
                display_name: DisplayName::from_str_lossy("test"),
            },
            role: Role::User,
        })
        .unwrap();

        assert_eq!(
            value,
            json!(
                {
                    "role": "user",
                    "device_secret": "1234",
                    "kind": "guest",
                    "display_name": "test"
                }
            )
        );
    }

    #[test]
    fn registered() {
        let value = serde_json::to_value(ClientParameters {
            device_secret: "1234".into(),
            kind: ClientKind::Registered {
                profile: PublicUserProfile::example_data(),
            },
            role: Role::User,
        })
        .unwrap();

        assert_eq!(
            value,
            json!(
                {
                    "device_secret": "1234",
                    "kind": "registered",
                    "role": "user",
                    "profile": {
                        "avatar_url": "https://gravatar.com/avatar/c160f8cc69a4f0bf2b0362752353d060",
                        "display_name": "Alice Adams",
                        "email": "alice@example.com",
                        "firstname": "Alice",
                        "lastname": "Adams",
                        "id": "00000000-0000-0000-0000-0000000a11c3",
                        "title": "",
                    }

                }
            )
        )
    }
}
